# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 03:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20160104_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('Home_team', models.CharField(max_length=50)),
                ('Away_team', models.CharField(max_length=50)),
                ('Home_line', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Away_line', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Home_preview', models.URLField(max_length=500)),
                ('Away_preview', models.URLField(max_length=500)),
            ],
            options={
                'db_table': 'game',
                'ordering': ('date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(default='NBA', max_length=50)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('point spread', 'Point Spread'), ('straight up', 'Straight Up')], default='point spread', max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_friend', to='registration.Friend')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_game', to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bets',
                'ordering': ('-created_at',),
            },
        ),
    ]
