# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Away_line',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='Home_line',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
