# Generated by Django 3.1.4 on 2020-12-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0003_auto_20201230_2157'),
        ('games', '0006_auto_20160418_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bet_friend', to='registration.friend'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bet_game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bet_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
