# Generated by Django 3.1.4 on 2020-12-30 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0008_auto_20201230_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bet_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
