# Generated by Django 3.1.4 on 2020-12-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0010_auto_20201230_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='winner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
